FROM node:22 AS dev

WORKDIR /usr/src/app

EXPOSE 3333

# Setting test environment
ENV NODE_ENV=test

# Copy all content
COPY . .

# Installing dependencies
RUN yarn

# Generating prisma client
RUN yarn prisma generate

ENTRYPOINT ["yarn", "dev"]
