services: 
  api: 
    container_name: "investment-bitcoin-api"
    build: 
      dockerfile: ./Dockerfile.local
    ports: 
     - "3333:3333"
    volumes:
      - ./node_modules:/usr/src/app/node_modules
      - .:/usr/src/app
    environment: 
      SERVER_PORT: ${SERVER_PORT}
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/test?schema=public"
      JWT_SECRET: ${JWT_SECRET}
      RABBITMQ_URL: "amqp://rabbitmq:5672"
      SEND_GRID_API_TOKEN: ${SEND_GRID_API_TOKEN}
      SEND_GRID_SENDER: ${SEND_GRID_SENDER}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  db:
    container_name: "investment-bitcoin-api-db"
    image: postgres:latest
    restart: always
    expose: 
      - "5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 3

  rabbitmq:
    container_name: "investment-bitcoin-rabbitmq"
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    expose:
      - "5672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 10s
      retries: 5
  
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
      
volumes: 
  pgdata:
  cache: