services: 
  api: 
    build: 
      dockerfile: ./Dockerfile.local
    ports: 
     - "3333:3333"
    volumes:
      - ./node_modules:/usr/src/app/node_modules
      - .:/usr/src/app
    environment: 
      SERVER_PORT: 3333

  db:
    image: postgres:latest
    restart: always
    expose: 
      - "5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 3

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    expose:
      - "5672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 10s
      retries: 5
      
volumes: 
  pgdata: