services: 
  api: 
    build: 
      dockerfile: ./Dockerfile.local
    ports: 
     - "3333:3333"
    volumes:
      - ./node_modules:/usr/src/app/node_modules
      - .:/usr/src/app
    environment: 
      SERVER_PORT: 3333
