@base_url = http://localhost:3333
@token = 
### Health check
GET {{base_url}}/health-check

### @name Register
POST {{base_url}}/register
Content-Type: application/json

{
  "name": "any-name",
  "password": "any-password",
  "email": "any@email.com",
  "balance": 100  
}

### @name Login
POST {{base_url}}/login
Content-Type: application/json

{
  "password": "any-password",
  "email": "any@email.com"
}

### @name Deposit
PATCH {{base_url}}/deposit
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "5599ab39-c556-4748-89da-dfcf6d268cae",
  "amount": 100
}



