@base_url = http://localhost:3333
@token = 
### Health check
GET {{base_url}}/health-check

### @name Register
POST {{base_url}}/client/register
Content-Type: application/json

{
  "name": "any-name",
  "password": "any-password",
  "email": "any@email.com",
  "balance": 100  
}

### @name Login
POST {{base_url}}/client/login
Content-Type: application/json

{
  "password": "any-password",
  "email": "any@email.com"
}

### @name Deposit
PATCH {{base_url}}/client/deposit
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "amount":1000000
}

### @name GetClientBalance
GET {{base_url}}/client/balance
Content-Type: application/json
Authorization: Bearer {{token}}

### @name GetBitcoinPrice
GET {{base_url}}/bitcoin
Content-Type: application/json
Authorization: Bearer {{token}}

### @name BuyBitcoin
POST {{base_url}}/client/buy-bitcoin
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "amount": 0.2
}

### @name GetInvestmentPosition
GET {{base_url}}/client/investments
Content-Type: application/json
Authorization: Bearer {{token}}



